In [2]:
import numpy as np

# 01

In [3]:
d = np.arange(1000000)

In [4]:
d

array([     0,      1,      2, ..., 999997, 999998, 999999])

# 02

In [5]:
x = np.zeros((4,4))

In [6]:
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# 03

In [7]:
y = np.ones((5,5))

In [8]:
y

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# 04

In [9]:
x = np.empty((3,3))

In [10]:
x

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 5.73116149e-321],
       [4.45060607e-308, 9.34609110e-307, 1.89146896e-307]])

# 05

In [11]:
list1 = [1,2,3,4,5] 

In [12]:
np.array(list1)

array([1, 2, 3, 4, 5])

# 06

In [13]:
x.shape

(3, 3)

# 07

In [14]:
x.reshape((3,3))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 5.73116149e-321],
       [4.45060607e-308, 9.34609110e-307, 1.89146896e-307]])

# 08

In [15]:
x.dtype

dtype('float64')

# 09

In [16]:
x.ndim

2

# 10

In [17]:
x.size

9

# 11

In [18]:
x.itemsize

8

# 12

In [19]:
x.data

# 13

In [20]:
np.linspace(0,2,10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

# 14

In [21]:
p = np.array([23,54,35,78])

In [22]:
r = p.copy()

In [23]:
r

array([23, 54, 35, 78])

In [24]:
p

array([23, 54, 35, 78])

# 15

In [25]:
np.empty(2)

array([1.53245026e-311, 0.00000000e+000])

# 16

In [26]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# 17

In [27]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# 18

In [28]:
np.full((3,3), 55, dtype=int)

array([[55, 55, 55],
       [55, 55, 55],
       [55, 55, 55]])

# 19

In [29]:
l1 = [23,34,12]

In [30]:
np.asarray(l1)

array([23, 34, 12])

# 20

In [31]:
x = np.arange(8.0) 

In [32]:
np.array_split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7.])]

# 21

In [33]:
a = np.array((1,2,3))



In [34]:
b = np.array((2,3,4))


In [35]:
np.column_stack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

# 22

In [36]:
np.logspace(4.0, 5.0, num=3)

array([ 10000.        ,  31622.77660168, 100000.        ])

# 23

In [37]:
np.mgrid[0:4, 0:4]


array([[[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]],

       [[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]]])

# 24

In [38]:
e = np.arange(12).reshape((4,3))

In [39]:
np.diag(e,k=1)

array([1, 5])

# 25

In [40]:
np.tri(4, 6, 0, dtype=int)

array([[1, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 0, 0]])

# 26

In [41]:
np.tril([[1,2,3],[4,5,6],[7,8,9]], -1)

array([[0, 0, 0],
       [4, 0, 0],
       [7, 8, 0]])

# 27

In [42]:
d = np.eye(2)

In [43]:
d

array([[1., 0.],
       [0., 1.]])

# 28

In [44]:
e = np.random.random((2,2))

In [45]:
e

array([[0.25924667, 0.84692947],
       [0.15791111, 0.05020186]])

# 29

In [46]:
np.all([[True,False],[True,True]])


False

# 30

In [47]:
np.any([[True, False], [True, True]])

True

# 31

In [48]:
data = np.arange(1, 5)




In [49]:
np.average(data)

2.5

# 32

In [50]:
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])

In [51]:
np.ceil(a)

array([-1., -1., -0.,  1.,  2.,  2.,  2.])

# 33

In [52]:
np.conjugate(1+2j)

(1-2j)

# 34

In [53]:
x = [1, 2, 3]

In [54]:

y = [4, 5, 6]

In [55]:
np.cross(x, y)


array([-3,  6, -3])

# 35

In [56]:
a = np.array([[1,2,3], [4,5,6]])

In [57]:
np.cumsum(a)

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

# 36

In [58]:
np.dot(3, 4)

12

# 37

In [59]:
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])

In [60]:
np.floor(a)

array([-2., -2., -1.,  0.,  1.,  1.,  2.])

# 38

In [61]:
a = np.array([[10, 7, 4], [3, 2, 1]])

In [62]:
np.median(a)

3.5

# 39

In [63]:
x = np.array([536870910, 536870910, 536870910, 536870910])

In [64]:
np.prod(x)

16

# 40

In [67]:
np.maximum([2, 3, 4], [1, 5, 2])

array([2, 5, 4])

# 41

In [68]:
a = np.array([[1,4],[3,1]])

In [69]:
np.sort(a)

array([[1, 4],
       [1, 3]])

# 42

In [70]:
a = np.array([[1, 2], [3, 4]])


In [71]:
np.std(a)

1.118033988749895

# 43

In [72]:
np.sum([[0, 1], [0, 5]])

6

# 44

In [73]:
x = np.arange(4).reshape((2,2))

In [75]:
x

array([[0, 1],
       [2, 3]])

In [74]:
np.transpose(x)

array([[0, 2],
       [1, 3]])

# 45

In [76]:
a = np.array([[1, 2], [3, 4]])

In [77]:
np.var(a)

1.25

# 46

In [78]:
a = np.array([[1, 4], [5, 6]])

In [79]:
b = np.array([[4, 1], [2, 2]])

In [80]:
np.vdot(a, b)

30

# 47

In [82]:
a = np.arange(10)

In [83]:
np.where(a < 5, a, 10*a)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

# 48

In [84]:
x = np.arange(8.0).reshape(2, 2, 2)

In [85]:
x

array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]])

In [86]:
np.hsplit(x, 2)

[array([[[0., 1.]],
 
        [[4., 5.]]]),
 array([[[2., 3.]],
 
        [[6., 7.]]])]

# 49

In [87]:
x = np.arange(6)

In [88]:
x = x.reshape((2, 3))

In [89]:
np.ones_like(x)

array([[1, 1, 1],
       [1, 1, 1]])

# 50

In [91]:
x = np.invert(np.array(13, dtype=np.uint8))

In [92]:
np.binary_repr(x, width=8)

'11110010'